[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer", args = ["--fix"] },
  { id = "trailing-whitespace" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  #{ id = "no-commit-to-branch", args = [
  #  "--branch",
  #  "main",
  #  "--pattern",
  #  "v\\d+\\.\\d+.\\d+",
  #] },
]

[[repos]]
repo = "local"
hooks = [
  { id = "taplo", name = "taplo", language = "system", entry = "taplo fmt", files = "\\.toml$" },
  { id = "cargo fmt", name = "cargo fmt", language = "system", entry = "cargo fmt", args = [
    "--check",
    "--all",
    "--",
    "--config",
    "format_generated_files=false",
  ], files = "\\.rs$" },
  { id = "cargo test", name = "cargo test", language = "system", entry = "cargo test", files = "\\.rs$" },
]
