[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[profile.dev]
debug = 2
opt-level = 0

[profile.release]
debug = 2
opt-level = 1
lto = false
codegen-units = 1

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
dress-up = { path = ".." }
uuid = { version = "1.18.1", default-features = false }
digest = { version = "0.10.7", default-features = false }
generic-array = { version = "1.3.5", features = ["const-default"] }
sha2 = "0.11.0"
shake = "0.1.0"

[[bin]]
name = "unaware"
path = "fuzz_targets/unaware.rs"
test = false
doc = false
bench = false

[[bin]]
name = "envlp_wrap"
path = "fuzz_targets/envlp_wrap.rs"
test = false
doc = false
bench = false

[[bin]]
name = "manifest_gen"
path = "fuzz_targets/manifest_gen.rs"
test = false
doc = false
bench = false
