#!/usr/bin/env python3

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def read_metrics_csv(path):
    """
    Read metrics CSV produced by metrics_parser.py.

    Returns a list of dictionaries with numeric values converted.
    """

    samples = []

    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            sample = {
                "timestamp": int(row["timestamp"]),
                "time_elapsed": int(row["time_elapsed"]),
                "iteration": int(row["iteration"]),
                "event": row["event"],
                "cov": int(row["cov"]),
                "exec_per_sec": int(row["exec_per_sec"]),
                "corp_count": int(row["corp_count"]),
                "corp_bytes": int(row["corp_bytes"]),
            }

            # Optional field from the improved parser
            if "ft" in row and row["ft"]:
                sample["ft"] = int(row["ft"])

            samples.append(sample)

    return samples


def plot_metrics(samples, output_path=None, use_iterations=False):
    """
    Plot fuzzing metrics.

    If use_iterations is False:
        x-axis = elapsed time in seconds

    If use_iterations is True:
        x-axis = fuzzer iteration number
    """

    if not samples:
        raise ValueError("No samples to plot.")

    if use_iterations:
        x = [s["iteration"] for s in samples]
        x_label = "Iteration"
    else:
        x = [s["time_elapsed"] for s in samples]
        x_label = "Elapsed time [s]"

    cov = [s["cov"] for s in samples]
    exec_per_sec = [s["exec_per_sec"] for s in samples]
    corp_count = [s["corp_count"] for s in samples]
    corp_bytes = [s["corp_bytes"] for s in samples]

    fig, axes = plt.subplots(4, 1, figsize=(12, 10), sharex=True)

    axes[0].plot(x, cov)
    axes[0].set_ylabel("Coverage")
    axes[0].set_title("Coverage over time")
    axes[0].grid(True)

    axes[1].plot(x, exec_per_sec)
    axes[1].set_ylabel("Exec/s")
    axes[1].set_title("Executions per second over time")
    axes[1].grid(True)

    axes[2].plot(x, corp_count)
    axes[2].set_ylabel("Corpus entries")
    axes[2].set_title("Corpus entries over time")
    axes[2].grid(True)

    axes[3].plot(x, corp_bytes)
    axes[3].set_ylabel("Corpus bytes")
    axes[3].set_title("Corpus size over time")
    axes[3].set_xlabel(x_label)
    axes[3].grid(True)

    fig.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=150)
        print(f"Plot written to: {output_path}")
    else:
        plt.show()


def plot_time_to_coverage(samples, target_coverages, output_path=None, use_iterations=False):
    """
    Plot coverage over time and mark when target coverage values are reached.
    """

    if not samples:
        raise ValueError("No samples to plot.")

    if use_iterations:
        x = [s["iteration"] for s in samples]
        x_label = "Iteration"
    else:
        x = [s["time_elapsed"] for s in samples]
        x_label = "Elapsed time [s]"

    cov = [s["cov"] for s in samples]

    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(x, cov, label="Coverage")

    for target in target_coverages:
        reached = next((s for s in samples if s["cov"] >= target), None)

        if reached is None:
            print(f"Coverage target {target} was not reached.")
            continue

        reached_x = reached["iteration"] if use_iterations else reached["time_elapsed"]

        ax.axhline(target, linestyle="--", linewidth=1)
        ax.axvline(reached_x, linestyle="--", linewidth=1)

        ax.scatter([reached_x], [reached["cov"]])

        ax.annotate(
            f"cov ≥ {target}\n{reached_x}",
            xy=(reached_x, reached["cov"]),
            xytext=(8, 8),
            textcoords="offset points",
        )

        print(
            f"Coverage target {target} reached at "
            f"{x_label.lower()}={reached_x}, "
            f"iteration={reached['iteration']}, "
            f"coverage={reached['cov']}"
        )

    ax.set_title("Time to reach coverage")
    ax.set_xlabel(x_label)
    ax.set_ylabel("Coverage")
    ax.grid(True)
    ax.legend()

    fig.tight_layout()

    if output_path:
        plt.savefig(output_path, dpi=150)
        print(f"Coverage target plot written to: {output_path}")
    else:
        plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Plot fuzzing metrics from CSV generated by metrics_parser.py."
    )

    parser.add_argument(
        "csv_file",
        type=Path,
        help="CSV file produced by the fuzz log parser.",
    )

    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Optional output image path, for example metrics.png.",
    )

    parser.add_argument(
        "--x-axis",
        choices=["time", "iteration"],
        default="time",
        help="Use elapsed time or fuzzer iteration as x-axis. Default: time.",
    )

    parser.add_argument(
        "--target-cov",
        type=int,
        nargs="*",
        default=None,
        help="Optional coverage target values to mark, for example: --target-cov 400 600 800",
    )

    parser.add_argument(
        "--target-output",
        type=Path,
        default=None,
        help="Optional output image path for the target coverage plot.",
    )

    args = parser.parse_args()

    samples = read_metrics_csv(args.csv_file)

    use_iterations = args.x_axis == "iteration"

    plot_metrics(
        samples,
        output_path=args.output,
        use_iterations=use_iterations,
    )

    if args.target_cov:
        plot_time_to_coverage(
            samples,
            target_coverages=args.target_cov,
            output_path=args.target_output,
            use_iterations=use_iterations,
        )


if __name__ == "__main__":
    main()
